### ISSUE TITLE
Canvas option error on Reactjs

### ISSUE THREAD

**Issue by rainstormza** [tipsy/bubbly-bg#18]
![image](https://user-images.githubusercontent.com/4003032/40555141-58faa180-6072-11e8-9f72-13eff095dd57.png)

```
  componentDidMount() {
    window.bubbly({
      colorStart: "#fff4e6",
      colorStop: "#ffe9e4",
      blur: 1,
      compose: "source-over",
      bubbleFunc: () => `hsla(${Math.random() * 50}, 100%, 50%, .3)`,
      canvas: document.getElementById("background") // error this line
    });
  }
```

I've tried to use your lib like this, it work fine until I added option canvase and then it throw an error.

Any help ? thanks :)

**Comment by tipsy** [comment]
Did you read through https://reactjs.org/docs/cross-origin-errors.html ? 

Seems weird that it only happens if you specify a canvas. How does the HTML for your canvas look?

**Comment by rainstormza** [comment]
Yes, I did.
I've tried 

![image](https://user-images.githubusercontent.com/4003032/40573094-f5185440-60e5-11e8-969d-6d33324c9d42.png)

but it does not work.

this is my test component 

![image](https://user-images.githubusercontent.com/4003032/40573083-c89d24ea-60e5-11e8-9a1f-8c6ea88d52bc.png)

I'm just curious that what canvas option exactly mean.
If I want background to show only inside this div (id = "background") so I have to use this option.
Am i right ?

you can try my repo. https://github.com/rainstormza/react-bubble

**Comment by tipsy** [comment]
You're right, but it has to be a `<canvas>` element ([docs](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API)), not a `<div>`.

Here is an example: https://tipsy.github.io/bubbly-bg/custom-canvas-example.html

Using a div shouldn't really give you the error you're seeing, but let me know if using a canvas fixes it.

**Comment by rainstormza** [comment]
it works, my bad
thanks for your help :)

![image](https://user-images.githubusercontent.com/4003032/40585097-d967b000-61d6-11e8-94fe-12ba4d8e077a.png)


![image](https://user-images.githubusercontent.com/4003032/40585088-c0e0083e-61d6-11e8-90e6-c75727063d08.png)
