### ISSUE TITLE
How to use with Reactjs

### ISSUE THREAD

**Issue by franva** [tipsy/bubbly-bg#20]
Tried to 
`npm i --save bubbly-bg`

then in my App.js

```
import bubbly from "bubbly-bg";

bubbly();
```

shows 

> Cannot find bubbly

**Comment by tipsy** [comment]
https://github.com/tipsy/bubbly-bg/issues/18

**Comment by pkkummermo** [comment]
I don't think bubbly has any exports. Have you tried `import * as bubbly from "bubbly-bg"`?
