### ISSUE TITLE
Distorted and fuzzy bubbles on canvas

### ISSUE THREAD

**Issue by lamego** [tipsy/bubbly-bg#22]
Hi! 
When using bubbly in a canvas element on a responsive page, the bubbles always look fuzzy and are often distorted.
Any idea how to fix this?

**Comment by tipsy** [comment]
Screenshot?

**Comment by lamego** [comment]
![screen shot 2018-11-16 at 11 28 09](https://user-images.githubusercontent.com/5329183/48619037-1a916280-e993-11e8-8db2-a10484b7baad.png)

**Comment by tipsy** [comment]
I've seen this happen when people attach bubbly to a small canvas and stretch it. How are you using it?

**Comment by lamego** [comment]
The canvas is set as a responsive element, has no width or height set, just an id and some css classes.

**Comment by tipsy** [comment]
What happens if you don't attach it to any element, just call `bubbly()`?

Edit: accidental phone close.

**Comment by lamego** [comment]
Like the default setting? The bubbles will be all over my page when I just need them at the header element.

**Comment by tipsy** [comment]
But they are clear?

**Comment by tipsy** [comment]
I guess bubbly attaches itself to your header, and then your header grows, which stretches bubbly.
