### ISSUE TITLE
not working with bulma css

### ISSUE THREAD

**Issue by manuel-rubio** [tipsy/bubbly-bg#26]
When I'm configuring in combination with Bulma CSS, this is not working at all. Is there any possibility to get compatibility with it?

**Comment by tipsy** [comment]
I haven't touched this in 3 years 😅 

What do you mean it doesn't work "with" Bulma? Bubbly should just attach to whatever, if I remember correctly.

**Comment by manuel-rubio** [comment]
@tipsy I have this website: https://lambdpad.com ... when I try to add the bulma css link:

```html
<link type='stylesheet' href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css"/>
```

The background is gone and the browser starts consuming a LOT of CPU. It's a static HTML with only one JS file and one CSS file so, it's easy download it and play with it.

**Comment by tipsy** [comment]
You can choose which element to attach bubbly to, could you try that?

```
    canvas: document.querySelector("#background"), // default is created and attached
```

**Comment by manuel-rubio** [comment]
yes, you're right... thank you!
