### ISSUE TITLE
bubble max_size

### ISSUE THREAD

**Issue by Jumbo125** [tipsy/bubbly-bg#27]
Hello 
Really got work!

Is it possible to set the maximum bubble size?
i will use the background on my tablet and the bubble looks really great.

Thank you
Best regards
Jumbo125

**Comment by tipsy** [comment]
Not sure if there is a config for that, but should be easy to change the code anyway 😊

**Comment by Jumbo125** [comment]
oh i see.
i try to change the code and pass it for me. It's not so easy, cause you wrote it really short :-)
i can't check the animation function. I can't find the position where you set the function.
After searching i found the function called:  requestAnimationFrame
I read some infos about this function and it's better to use this an not the javascript intervall function. So i'm happy that you use it. 
But the animation jerks a little bit. I can't find a solution. Is it right, that the problem is the hardware? i mean the Montior fps/hz

thank you

**Comment by tipsy** [comment]
I haven't touched this in many years, but I see that it's very choppy.. They probably changed something with how browsers work. Let me have a look.

**Comment by Jumbo125** [comment]
Oh thank you

But, Let it go. I use another solution, because I want to use it on my tablet. The bubble function is really nice, but it needs too much browser ressources... My tablet give up, if I load the side. 

Thank you for your help

**Comment by tipsy** [comment]
It seems the issue is with `context.shadowBlur`, sometimes in the last few years, this has become very expensive to call.

**Comment by tipsy** [comment]
> The bubble function is really nice, but it needs too much browser ressources... My tablet give up, if I load the side.

Managed to fix this, all examples are running at 60fps with little CPU usage now (used to be 8fps for the last two here).

**Comment by Jumbo125** [comment]
ohhhh how do you do this!? great
where in the code ist the line, which set the fps????

**Comment by tipsy** [comment]
You don't have to set the fps manually, it should match system settings.

**Comment by tipsy** [comment]
I just tested it on my phone. It takes a while to get started now, but once it starts its running smoothly.

**Comment by tipsy** [comment]
(demo link in readme is updated)

**Comment by Jumbo125** [comment]
okay. thank you
was it difficult to set it up?
how do you do it?

**Comment by tipsy** [comment]
You don't have to do anything other than use the new file in the dist folder

You can also set the bubble size using the radius function config option.
