### ISSUE TITLE
How to disable or Remove Bubbly ?

### ISSUE THREAD

**Issue by aligundogdu** [tipsy/bubbly-bg#6]
Hi, 

I use this library with the spa and just want to show it on the login page.
I want to delete the canvas after the user has logged in.
Is there a method for that?

**Comment by tipsy** [comment]
This is a one way ticket currently. Feel free to submit a PR though.

**Comment by tipsy** [comment]
@aligundogdu I just released 0.2.3, which will stop animation once you remove the canvas from the dom,
which you can do with ` document.body.removeChild(document.querySelector("canvas"));`. 0.2.3 also supports using a custom canvas.

**Comment by aligundogdu** [comment]
Hi,
Thank you.
Regards.
