### ISSUE TITLE
SVG images instead of bubbles

### ISSUE THREAD

**Issue by nemanjapetrovic** [tipsy/bubbly-bg#9]
Hi,

bubbly-bg is a great repo.

It would be great to add a new feature as instead of bubbles to load SVG images, what do you think?

**Comment by tipsy** [comment]
Thanks - I'm having a little trouble imagining how SVG images would be useful. They would be rotated randomly and travelling at random speeds and in random directions. I'm not sure it works well for anything other than bubbles. What kind of shapes were you thinking about? 🤔

**Comment by nemanjapetrovic** [comment]
I would probably add it to the project I am working on right now, it's about beer, something like beer notebook, and would have all round beer bottle caps spinning randomly in random directions. :)

**Comment by tipsy** [comment]
Sounds like a very specific use case 😄 
You can just fork the repo and replace the bubble-drawing part with `drawImage`: https://github.com/tipsy/bubbly-bg/blob/master/src/bubbly-bg.js#L43-L46

**Comment by nemanjapetrovic** [comment]
Yeah, would probably do it.
